build:
  image: default-bionic
  environment:
    php: 7.4
    variables:
      XDEBUG_MODE: coverage
  dependencies:
    override:
      - composer install --no-interaction --no-scripts
    after:
      - cp -n .env.example .env
      - php bin/build-paths
  tests:
    override:
      - command: vendor/bin/phpunit
        coverage:
          file: build/phpunit/coverage/coverage.clover.xml
          format: clover

  nodes:
    php-analysis:
      tests:
        override:
          - vendor/bin/phpcs
          - vendor/bin/phpstan analyze
          - php-scrutinizer-run --enable-security-analysis
    php-7.4:
      environment:
        php: 7.4
    php-8.0:
      environment:
        php: 8.0
    php-8.1:
      environment:
        php: 8.1

checks:
  php: true

filter:
  excluded_paths:
    - tests/
  dependency_paths:
    - vendor/
    - assets/node_modules/
