services:
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      target: app
      args:
        PHP_VERSION: "8.1"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app
    environment:
      HOST_UID: "${HOST_UID}"
      HOST_GID: "${HOST_GID}"
      XDEBUG_CONFIG: "${APP_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      XDEBUG_MODE: "${APP_XDEBUG_MODE:-debug,develop,trace}"
    depends_on:
      - selenium

  webserver:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      target: webserver
    extra_hosts:
      - "host.docker.interal:host-gateway"
    networks:
      - app
    environment:
      SERVER_NAME: "${SERVER_NAME:-localhost}"
      SERVER_PORT: "${SERVER_PORT:-80}"
      APP_NAME: app
      APP_PORT: 9000
      WEB_ROOT: /var/www/html/browser
    depends_on:
      - app

  selenium:
    image: "selenium/standalone-chrome"
    networks:
      - app
    volumes:
      - "/dev/shm:/dev/shm"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app:
    driver: bridge
