services:
  app:
    build:
      target: app-workspace
      args:
        UNMINIMIZE: true
        GIT_USER:
        GIT_EMAIL:
        GIT_DEFAULT_BRANCH: "master"
        GIT_INSTALL_GCM: false
        LANG: "${LANG}"
        TZ: "${TZ}"
    environment:
      ZSH_THEME: "powerlevel10k/powerlevel10k"
      TERM: "${TERM}"
    volumes:
      # Source
      - ".:/var/www/html"
      # Credentials
      - "~/.config/composer/auth.json:/home/saveyour/.config/composer/auth.json"
      # Misc
      - "vscode:/root/.vscode-server"

  webserver:
    build:
      target: webserver-local
    networks:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: "${SERVER_NAME}"
      LANG: "${LANG}"
      TZ: "${TZ}"
      TERM: "${TERM}"
    volumes:
      - ".:/var/www/html:ro"

  selenium:
    environment:
      TERM: "${TERM}"

volumes:
  vscode:
    driver: local
